# GET VIRTUAL ENVIRONMENT =============================================
venv_get:
	./get_pipenv.sh

# REMOVE VIRTUAL ENVIRONMENT =============================================
venv_remove:
	./remove_pipenv.sh
