# GET VIRTUAL ENVIRONMENT =============================================
venv_get:
	./get_poetryenv.sh

# REMOVE VIRTUAL ENVIRONMENT ==========================================
venv_remove:
	@echo "===removing virtual environment==="
	poetry env remove python
