# GET VIRTUAL ENVIRONMENT =============================================
venv_get:
	./get_virtualenv.sh

# REMOVE VIRTUAL ENVIRONMENT ==========================================
venv_remove:
	./remove_virtualenv.sh
